---
title: "PIR_MOM"
author: "James E. Pustejovsky"
date: "Friday, February 06, 2015"
output: html_document
---

```{r}
library(knitr)
opts_chunk$set(cache = FALSE)
options(width = 150)
library(ARPobservation)

data(Moes)
Bootstraps <- 10000
seed <- NULL
```

# Carl
```{r Carl}
with(subset(Moes, Case == "Carl"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed))

with(subset(Moes, Case == "Carl"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed, old = TRUE))
```

# Charles
```{r Charles}
with(subset(Moes, Case == "Charles"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed))

with(subset(Moes, Case == "Charles"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed, old = TRUE))
```

# Chuck
```{r Chuck}
with(subset(Moes, Case == "Chuck"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed))

with(subset(Moes, Case == "Chuck"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed, old = TRUE))

```

# James
```{r James}
with(subset(Moes, Case == "James"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed))

with(subset(Moes, Case == "James"),
     PIR_MOM(PIR = outcome, phase = Phase, base_level = "No Choice",
             intervals = 80, interval_length = 15, rest_length = 5, 
             Bootstraps = Bootstraps, seed = seed, , old = TRUE))

```
